# encoding: utf-8

require 'helpers/faye'

# Public: A worker that processes chat messages
# and broadcast them to a given destination.
class MessagesWorker
  
  include Worker::Base # Scripts, Daemons & Redis
  include Worker::REnv # Rails Environment
  include Worker::Queue # Queue Connector
  
  include Worker::Helper::Faye # Faye Broadcaster
  
  queue :messages # The AMQP queue from which messages should be pop'ed when available
  
  # Public: The action performed as soon as there's a new message in the queue
  # 
  # message - The Hashr options should contain (default: Hashr.new):
  #           :topic_id - The BSON id of the type of chat the message is being sent to (cloud of friendship)
  #           :topic_type - The type of chat the message is being sent to (cloud or friendship)
  #           :user - A depiction of the user object reference can be found in "app/views/api/v1/messages/base.rabl"
  #           :content - The content text of the message
  #           :timestamp - The time the message was sent
  #           :client_id - The ID generated by the client requesting to send the message
  # 
  # Requests faye to broadcast the message to the given channel.
  def perform(message=Hashr.new)
    
    log.info("Picked message from messages queue")
    log.debug("Message payload: #{message}")
    broadcast "/#{message.topic_type}/#{message.topic_id}/chat", message
    
  end

end