development:
  twitter:
    consumer_key: J1FiSKDKD9ev4xAVO3cLOw
    consumer_secret: djHBQOop2qIeUDb9xS0MPcwihSSHDWEhHoZ7aVCjOCs
  facebook:
    app_key: 213007855430354
    app_secret: 442e0c7b6e1c2c26c0ef04fa1feb173c
      
production:
  twitter:
    consumer_key: nft8CQEyNxLpwOt37pKYA
    consumer_secret: XHw0N6ZylF6EHoxZay4jKA8DNdKSi6M5w659hbmpzw8
  facebook:
    app_key: 255258867845902
    app_secret: 4151911ea59e2aa64276089189157f00