development:
  url: http://127.0.0.1
  faye_port: 9191
  twitter:
    consumer_key: J1FiSKDKD9ev4xAVO3cLOw
    consumer_secret: djHBQOop2qIeUDb9xS0MPcwihSSHDWEhHoZ7aVCjOCs
  facebook:
    app_key: 213007855430354
    app_secret: 442e0c7b6e1c2c26c0ef04fa1feb173c
  tire:
    host: 127.0.0.1
    port: 9200
  redis:
    host: 127.0.0.1
    port: 6379
  rackspace_cloudfiles:
    username: zeeraw
    api_key: a807350d725e1ce3202aac3ff08a3ac1
    fog_directory: cloudsdale_development_uploads
    fog_host: http://c775851.r51.cf2.rackcdn.com
  faye:
    host: 127.0.0.1
    port: 9191
    token: 650659cd4801877e56a176d70dcd4851fa4c86327b3b9439fef2fbf77543b8e2
    redis: 
      host: 127.0.0.1
      port: 6379
    
      
production:
  url: http://cloudsdale.org
  faye_port: 9191
  tire_port: 9200
  twitter:
    consumer_key: nft8CQEyNxLpwOt37pKYA
    consumer_secret: XHw0N6ZylF6EHoxZay4jKA8DNdKSi6M5w659hbmpzw8
  facebook:
    app_key: 255258867845902
    app_secret: 4151911ea59e2aa64276089189157f00
  tire:
    host: 50.57.151.151
    port: 9200
  redis:
    host: 127.0.0.1
    port: 6379
  rackspace_cloudfiles:
    username: zeeraw
    api_key: a807350d725e1ce3202aac3ff08a3ac1
    fog_directory: cloudsdale_production_uploads
    fog_host: http://c775850.r50.cf2.rackcdn.com
  faye:
    host: 127.0.0.1
    port: 9191
    token: e854ebd38d63042f210214f95b5281b8934b359821cade18e52549e3788ef713
    redis: 
      host: 127.0.0.1
      port: 6379
      password: b162cee3d5d2a1df34d356bb12249f52
    