defaults: &defaults

  uploader:
    storage: 'file'

  email:
    host: localhost
    port: 1025
    url:
      host: local.cloudsdale.org
      port: 3000

  youtube:
    dev_key: AI39si4HazJyHrwMi9zVHSTJRgMMnndNL5gfZz9nVAuNIoFndhb5J5rdO97FKrnJox_V0bVTcs3bOfes7yyW_Rylkvhtly2y_g

  twitter:
    consumer_key: mHnUVYK5NUfk0IHbqruZcA
    consumer_secret: Jlz13rBFDrPMKvr5EcWmNHaB6YwYHH1FCCASGFdOSkY

  facebook:
    app_key: 213007855430354
    app_secret: 442e0c7b6e1c2c26c0ef04fa1feb173c

  redis:
    host: 127.0.0.1
    port: 6379

  rabbit:
    host: localhost
    user: guest
    pass: guest

  faye:
    path: push
    schema: http
    secure_schema: https
    host: local.cloudsdale.org
    port: 8000
    secure_port: 44300
    token: 650659cd4801877e56a176d70dcd4851fa4c86327b3b9439fef2fbf77543b8e2
    inhouse_host: 127.0.0.1

development:
  <<: *defaults

  url: http://local.cloudsdale.org:3000
  asset_url: http://local.cloudsdale.org:3000

  rackspace_cloudfiles:
    username: zeeraw
    api_key: fb02d3d2336d887b81c7401d522ea393
    fog_directory: cloudsdale_development_uploads
    fog_host: https://c775851.ssl.cf2.rackcdn.com

test:
  <<: *defaults


production:
  <<: *defaults

  url: http://www.cloudsdale.org
  asset_url: https://c776950.ssl.cf2.rackcdn.com

  email:
    user_name: cloudsdale
    password: secret1234
    address: smtp.sendgrid.net
    domain: cloudsdale.org
    port: 587
    url:
      host: www.cloudsdale.org
      port: 80

  uploader:
    storage: 'fog'

  youtube:
    dev_key: AI39si4HazJyHrwMi9zVHSTJRgMMnndNL5gfZz9nVAuNIoFndhb5J5rdO97FKrnJox_V0bVTcs3bOfes7yyW_Rylkvhtly2y_g

  twitter:
    consumer_key: nft8CQEyNxLpwOt37pKYA
    consumer_secret: XHw0N6ZylF6EHoxZay4jKA8DNdKSi6M5w659hbmpzw8

  facebook:
    app_key: 255258867845902
    app_secret: 4151911ea59e2aa64276089189157f00

  rackspace_cloudfiles:
    username: zeeraw
    api_key: fb02d3d2336d887b81c7401d522ea393
    fog_directory: cloudsdale_production_uploads
    fog_host: https://c775850.ssl.cf2.rackcdn.com

  faye:
    path: push
    schema: http
    secure_schema: https
    host: push.cloudsdale.org
    port: 80
    secure_port: 443
    token: e854ebd38d63042f210214f95b5281b8934b359821cade18e52549e3788ef713
    inhouse_host: push.cloudsdale.org


