defaults: &defaults

  url: http://www.cloudsdale.dev
  asset_url: http://www.cloudsdale.dev
  session_key: .cloudsdale.dev

  avatar:
    http:   http://avatar.cloudsdale.dev
    https:  http://avatar.cloudsdale.dev

  cdn:
    alias: cloudsdale
    secret: a2a1710c0803a98faacb370e297a5a7a
    key: 34e6b64511c260329d44927bcd4a09b90519be1ff
    avatar_zone:
      id: 96822
      type: pull

  uploader:
    storage: 'file'

  email:
    host: localhost
    port: 1025
    url:
      host: www.cloudsdale.dev
      port: 80

  youtube:
    dev_key: AI39si4HazJyHrwMi9zVHSTJRgMMnndNL5gfZz9nVAuNIoFndhb5J5rdO97FKrnJox_V0bVTcs3bOfes7yyW_Rylkvhtly2y_g

  github:
    client_id: b47fc28f752aaa49c583
    client_secret: b31ba47d6d555cea720ce7493192879f61f6162a

  twitter:
    consumer_key: mHnUVYK5NUfk0IHbqruZcA
    consumer_secret: Jlz13rBFDrPMKvr5EcWmNHaB6YwYHH1FCCASGFdOSkY

  facebook:
    app_key: 213007855430354
    app_secret: 442e0c7b6e1c2c26c0ef04fa1feb173c

  redis:
    host: 127.0.0.1
    port: 6379

  rabbit:
    host: localhost
    user: guest
    pass: guest

  faye:
    path: push
    schema: http
    secure_schema: https
    host: push.cloudsdale.dev
    port: 8000
    secure_port: 443
    token: 650659cd4801877e56a176d70dcd4851fa4c86327b3b9439fef2fbf77543b8e2
    inhouse_host: push.cloudsdale.dev

development:
  <<: *defaults

  rackspace_cloudfiles:
    username: zeeraw
    api_key: fb02d3d2336d887b81c7401d522ea393
    fog_directory: cloudsdale_development_uploads
    fog_host: https://c775851.ssl.cf2.rackcdn.com

test:
  <<: *defaults


production:
  <<: *defaults

  url: http://www.cloudsdale.org
  asset_url: https://c776950.ssl.cf2.rackcdn.com
  session_key: .cloudsdale.org

  avatar:
    http:   http://avatar.cdn.cloudsdale.org
    https:  https://avatar-cloudsdale.netdna-ssl.com

  email:
    user_name: cloudsdale
    password: secret1234
    address: smtp.sendgrid.net
    domain: cloudsdale.org
    port: 587
    url:
      host: www.cloudsdale.org
      port: 80

  uploader:
    storage: 'fog'

  youtube:
    dev_key: AI39si4HazJyHrwMi9zVHSTJRgMMnndNL5gfZz9nVAuNIoFndhb5J5rdO97FKrnJox_V0bVTcs3bOfes7yyW_Rylkvhtly2y_g

  github:
    client_id: 631174526c743d4a9f51
    client_secret: 0e3cae3a8b61f3c4536c33f6c3e38bb297e0712d

  twitter:
    consumer_key: nft8CQEyNxLpwOt37pKYA
    consumer_secret: XHw0N6ZylF6EHoxZay4jKA8DNdKSi6M5w659hbmpzw8

  facebook:
    app_key: 255258867845902
    app_secret: 4151911ea59e2aa64276089189157f00

  rackspace_cloudfiles:
    username: zeeraw
    api_key: fb02d3d2336d887b81c7401d522ea393
    fog_directory: cloudsdale_production_uploads
    fog_host: https://c775850.ssl.cf2.rackcdn.com

  faye:
    path: push
    schema: http
    secure_schema: https
    host: push.cloudsdale.org
    port: 80
    secure_port: 443
    token: e854ebd38d63042f210214f95b5281b8934b359821cade18e52549e3788ef713
    inhouse_host: push.cloudsdale.org


