development:
  url: http://127.0.0.1
  faye_port: 9191
  twitter:
    consumer_key: J1FiSKDKD9ev4xAVO3cLOw
    consumer_secret: djHBQOop2qIeUDb9xS0MPcwihSSHDWEhHoZ7aVCjOCs
  facebook:
    app_key: 213007855430354
    app_secret: 442e0c7b6e1c2c26c0ef04fa1feb173c
  redis:
    host: 127.0.0.1
    port: 6379
  rackspace_cloudfiles:
    username: zeeraw
    api_key: a807350d725e1ce3202aac3ff08a3ac1
    fog_directory: cloudsdale_development_uploads
    fog_host: http://c775851.r51.cf2.rackcdn.com
    
      
production:
  url: http://cloudsdale.org
  faye_port: 9191
  twitter:
    consumer_key: nft8CQEyNxLpwOt37pKYA
    consumer_secret: XHw0N6ZylF6EHoxZay4jKA8DNdKSi6M5w659hbmpzw8
  facebook:
    app_key: 255258867845902
    app_secret: 4151911ea59e2aa64276089189157f00
  redis:
    host: 127.0.0.1
    port: 6379
  rackspace_cloudfiles:
    username: zeeraw
    api_key: a807350d725e1ce3202aac3ff08a3ac1
    fog_directory: cloudsdale_production_uploads
    fog_host: http://c775850.r50.cf2.rackcdn.com