development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: cloudsdale
  pool: 5
  username: cloudsdale
  password: u3197uih034L83e02y4y1e1562n1Vp
  timeout: 5000
  host: 127.0.0.1
