pid: /opt/pids/faye_thin.pid
log: /opt/logs/faye_thin.log
timeout: 30
port: 9191
max_conns: 1024
rackup: /opt/app/faye.ru
max_persistent_conns: 512
environment: production
address: 127.0.0.1
servers: 1
daemonize: true