defaults: &defaults
  options:
    use_utc: true
    use_activesupport_time_zone: true
    identity_map_enabled: true

development:
  <<: *defaults

  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] || "mongodb://localhost:27017/cloudsdale" %>
      options:
        safe: false
        consistency: :strong

production:
  <<: *defaults

  sessions:
    default:
      uri: <%= ENV['MONGO_URL'] || "mongodb://mongo:27017/cloudsdale" %>
      options:
        safe: false
        consistency: :strong