defaults: &defaults
  options:
    use_utc: true
    use_activesupport_time_zone: true
    identity_map_enabled: true

development:
  <<: *defaults

  sessions:
    default:
      database: cloudsdale
      hosts:
        - <%= ENV['MONGOID_URL'] || "www.cloudsdale.dev:27017" %>

      options:
        safe: false
        consistency: :strong

production:
  <<: *defaults

  sessions:
    default:
      database: cloudsdale
      username: cloudsdale
      password: 62148f9b9158ead23c8ace8c1b081055d068a216d3096b95f6399508f6674d6e3bf6ebbfcdbe85b126b431a8674a1d59370918683781976be5cfeba2c89f94b4

      hosts:
        - 198.27.74.148:27017
        - 167.114.0.157:27017

      options:
        safe: false
        consistency: :strong
        options:
          read: :secondary
          write:
            w: :majority